# This file contains values from Cookiecutter

default_context:
  project_name: "librus-apix"
  project_description: "Librus Synergia web scraper."
  organization: "librus-apix"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "Poroknights"
  email: "whinitc2@gmail.com"
  version: "0.2.6"
  line_length: "88"
  create_example_template: "cli"
