name: Run mock tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      librus-apix-mock:
        image: ghcr.io/rustysnek/librus-apix-mock:latest
        ports:
          - 8000:8000
        options: --env PYTHONUNBUFFERED=1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Run tests
        run: pytest
        env:
          PYTHONUNBUFFERED: 1

